name: Build & Release APK

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    name: Build Android Release APK and create Release
    runs-on: ubuntu-latest
    env:
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Flutter pub get
        working-directory: ./
        run: flutter pub get

      - name: Decode keystore (if provided)
        if: ${{ env.KEYSTORE_BASE64 != '' }}
        run: |
          echo "Decoding keystore from secrets..."
          echo "$KEYSTORE_BASE64" | base64 --decode > ./android/app/keystore.jks
          echo "keystore.jks created"

      - name: Write key.properties (if keystore provided)
        if: ${{ env.KEYSTORE_BASE64 != '' }}
        run: |
          echo "storePassword=${KEYSTORE_PASSWORD}" > android/key.properties
          echo "keyPassword=${KEY_PASSWORD}" >> android/key.properties
          echo "keyAlias=${KEY_ALIAS}" >> android/key.properties
          echo "storeFile=app/keystore.jks" >> android/key.properties

      - name: Build APK (release)
        env:
          JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
        run: flutter build apk --release --target-platform android-arm64 --split-per-abi

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: release-${{ github.run_number }}
          name: Release ${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APKs to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
          asset_name: app-arm64-v8a-release.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload x86 APK (if exists)
        if: ${{ hashFiles('build/app/outputs/flutter-apk/app-x86_64-release.apk') != '' }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-x86_64-release.apk
          asset_name: app-x86_64-release.apk
          asset_content_type: application/vnd.android.package-archive
